# Generated by Django 4.0.4 on 2022-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('age', models.CharField(max_length=70, verbose_name='سن')),
                ('phoneNumber', models.CharField(max_length=300, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('telegramId', models.CharField(max_length=100, verbose_name='تلگرام')),
                ('graduation', models.CharField(max_length=300, verbose_name='تحصیلات')),
                ('abilities', models.CharField(max_length=300, verbose_name='مهارت ها')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='درباره من')),
            ],
            options={
                'verbose_name': 'خصوصیت',
                'verbose_name_plural': 'اطلاعات شخصی',
            },
        ),
    ]
