# Generated by Django 4.0.4 on 2022-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_main', '0002_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('year', models.CharField(max_length=300, verbose_name='سال انشار')),
                ('link', models.CharField(max_length=300, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='uploads/projects', verbose_name='تصویر')),
            ],
        ),
    ]
