# Generated by Django 4.0.4 on 2022-06-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_main', '0003_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
    ]
